Updated Sector File Descriptor for new URL
VATSIM-UK/uk-controller-pack pull request #264
Opened 2022-02-24 10:27 UTC by hsugden

Fixes #261

# Summary of changes

With the changes to the UK domain, we now need to use vatsim.uk

This change fixes that

2022-02-24 14:22 UTC, GeekPro101 approved these changes

2022-02-25 22:01 UTC, KHardern requested changes
the shortened URL is just a redirect, which is likely to cause errors. Update the domain is fine.

have you tested this?

2022-02-25 22:04 UTC, cpawley commented on UK/Data/Sector/VATUK_Euroscope_files.txt
> +URL:http://www.vatsim.uk/VATSIM_UK_Sector_Provider.txt
```suggestion
URL:http://www.vatsim.uk/files/sector/esad/VATUK_Euroscope_files.txt
```

2022-02-25 22:04 UTC, cpawley commented on UK/Data/Sector/VATUK_SectorFileProviderDescriptor.txt
> +URL:http://www.vatsim.uk/VATSIM_UK_Sector_Provider.txt
```suggestion
URL:http://www.vatsim.uk/files/sector/esad/VATUK_Euroscope_files.txt
```

2022-02-25 22:05 UTC, KHardern commented
I'm going to commit what I think works in my other branch. I think the redirects work, but it needs an update of the download time to work properly.

2022-02-27 13:37 UTC, luke11brown approved these changes

2022-02-27 13:37 UTC, merged