profiles: Update Edinburgh Symbology
VATSIM-UK/uk-controller-pack pull request #295
Opened 2022-05-04 14:11 UTC by SamLefevre

Fixes #293 

# Summary of changes

Update Symbology to new style

# Screenshots (if necessary)

Edinburgh Radar_1
![image](https://user-images.githubusercontent.com/64741876/166699499-72f8a2ec-eb63-401a-bc95-6e1befa1ff91.png)

Edinburgh Radar_2
![image](https://user-images.githubusercontent.com/64741876/166699539-56dcd3ca-d7fa-487f-8e56-f46bc976bb2a.png)

Edinburgh Radar_3
![image](https://user-images.githubusercontent.com/64741876/166699587-74f08900-1354-4310-9801-2cdf5a840a36.png)

Edinburgh Radar_4
![image](https://user-images.githubusercontent.com/64741876/166699622-3cceefeb-e26e-4bcf-9005-2f469c5b95d2.png)

2022-05-19 09:49 UTC, luke11brown commented
Given the Sc_App General file has been modified, how does this affect the Glasgow displays?

2022-05-19 09:51 UTC, luke11brown commented on UK/Data/Settings/Local/Edinburgh/Symbology.txt
> +Sector:active sector background:8747638:3.5:0:0:7
I'm not sure these colours are reflective of the InNOVA displays... 
I'd be careful of just colour picking from what is possibly an over/under exposed image of the real system.
I'd like some input from the users of the real system to compare.

2022-05-19 10:01 UTC, luke11brown commented on UK/Data/Settings/Sc_APP/Sc_APP_General.txt
> -m_AutoAssumeOnGroundStateChangeButton:0
These settings, related to ES r29 need to remain

2022-05-19 10:11 UTC, luke11brown requested changes
Please see above comments

2022-05-20 13:32 UTC, SamLefevre commented
> Given the Sc_App General file has been modified, how does this affect the Glasgow displays?

The Glasgow profiles at the moment use the GEO extended centrelines, so the profile shouldn't be effected

2022-05-22 11:49 UTC, luke11brown approved these changes

2022-05-22 11:49 UTC, luke11brown commented
Still unsure about colour selection

2022-06-15 20:33 UTC, SamLefevre commented
![image](https://user-images.githubusercontent.com/64741876/173921723-4c0fb61f-218f-4bb3-aca7-830f4edd08aa.png)
![image](https://user-images.githubusercontent.com/64741876/173921797-4be75f6b-6442-49cb-b367-95352564acc2.png)

Made the inactive and active colour more like real world, however the default land colour doesn't make it look great

2022-09-07 12:23 UTC, merged