Fixes #290 - Flight information Display
VATSIM-UK/uk-controller-pack pull request #410
Opened 2023-05-29 23:59 UTC by SamLefevre

Fixes #290 

# Summary of changes

Add FID to simulate https://databeacon.aero/simplifid/

# Screenshots (if necessary)

![image](https://github.com/VATSIM-UK/uk-controller-pack/assets/64741876/d896b11e-ba23-4162-a6f0-b8dd12f0b0bf)

2023-05-31 23:42 UTC, SamLefevre commented
I'll finish the rest of the voice.txt by the end of the week

2023-06-03 14:27 UTC, luke11brown commented
If simulating an ADS-B derived display, would it be an idea to get it to use S-Mode correlation in general settings?

2023-06-25 12:01 UTC, kye-taylor requested changes
I think we could include London and Scottish Infomation positions here also.

Looks really clean and great, As for the ATIS information, I'm not sure what best to settle with so I have to guess a little. Feel free to change it!

2023-06-25 14:55 UTC, luke11brown commented on UK/Data/Settings/Voice_FID.txt
Can we also include all the positions listed here?

https://www.vatsim.uk/atc/endorsements#endorsement-afis

2023-06-28 17:46 UTC, kye-taylor approved these changes

2023-06-28 21:17 UTC, luke11brown approved these changes

2023-06-28 21:19 UTC, merged