Fixes #654 - vATIS Profile to include EGPO
VATSIM-UK/uk-controller-pack pull request #655
Opened 2024-03-21 23:44 UTC by Trodaiche

Fixes #654

# Summary of changes

Updated as per issue

# Screenshots (if necessary)

N/A

2024-03-24 06:27 UTC, luke11brown commented
@RedstonePilot Able to take a look at this pr?

2024-03-24 12:01 UTC, RedstonePilot commented
Unfortunately I'm away for the next week. Can maybe take a look wc 01/04. I don't have much to do with the packs vAtis but will take a look when I'm free!

2024-03-31 11:27 UTC, RedstonePilot commented
Seems to be an excess of data. Assuming you made the change in the vATIS window then used what it spat out?

2024-03-31 11:52 UTC, RedstonePilot requested changes
I'm not going to spend all my time reviewing this given that a lot of the frequencies seem to be wrong. If you can fix those then I'll review the whole thing. I would suggest just adding the EGPO profile in rather than editing the whole file, which seems to have lead to mistakes.

2024-03-31 11:52 UTC, RedstonePilot commented on UK/vATIS/UK - Scottish AC.json
> +              "high": 1013,
Seems to be an overlap here. 1013 is the high point while the next block starts at 1012

2024-03-31 11:52 UTC, RedstonePilot commented on UK/vATIS/UK - Scottish AC.json
> +  "id": "b1431b6d-4010-48e4-bd25-3e0ae3a1d5fc",
The id isn't required as far as I know. Not a big issue but increases the file size.

2024-03-31 11:52 UTC, RedstonePilot commented on UK/vATIS/UK - Scottish AC.json
> +          "airportConditions": "DEPARTING AIRCRAFT MAKE INITIAL CONTACT WITH SCOTTISH CONTROL ON 135.525",
Is this the right frequency? The old one has 135.530 while this says 135.525 (seems to be the pre .833khz).

2024-03-31 11:52 UTC, RedstonePilot commented on UK/vATIS/UK - Scottish AC.json
> +          "airportConditions": "DEPARTING AIRCRAFT MAKE INITIAL CONTACT WITH SCOTTISH CONTROL ON 135.525",
same as before. Old frequency.

2024-03-31 11:52 UTC, RedstonePilot commented on UK/vATIS/UK - Scottish AC.json
> +          "airportConditions": "DEPARTING AIRCRAFT MAKE INITIAL CONTACT WITH SCOTTISH CONTROL ON 135.85",
Frequency should be 135.855. You've missed a 5!

2024-03-31 12:35 UTC, Trodaiche commented
This was an export of the original profile with only the EGPO updated. I can't answer for the original file

2024-03-31 12:35 UTC, closed without merging

2024-03-31 18:29 UTC, RedstonePilot commented
Did you mean to close the pr? If so I'm more than happy to add the required changes I just don't know who has top down responsibility.