Fixes #824 - Remove Cambridge (EGSC) Director/Radar frequencies
VATSIM-UK/uk-controller-pack pull request #825
Opened 2024-08-15 08:19 UTC by AdriTheDev

Fixes #824 

# Summary of changes

Removed Cambridge (EGSC) Director/Radar frequencies (Ref https://github.com/VATSIM-UK/UK-Sector-File/issues/5416)

# Screenshots (if necessary)

N/A

2024-08-15 13:46 UTC, PLM1995 requested changes

2024-08-15 13:46 UTC, PLM1995 commented on UK/Data/Settings/Voice.txt
> -AG:EGSC_A_APP:120.965
As mentioned on the SF issues, this one needs keeping

2024-09-04 07:00 UTC, luke11brown approved these changes

2024-09-04 08:43 UTC, luke11brown approved these changes

2024-09-04 08:43 UTC, merged