Fixes #888 - Update Newcastle Symbology
VATSIM-UK/uk-controller-pack pull request #889
Opened 2024-10-13 12:39 UTC by SamLefevre

Fixes #888 

# Summary of changes

Updated Newcastle Profile to closer match new system.

# Screenshots (if necessary)
![image](https://github.com/user-attachments/assets/d6147fa8-e290-45b3-8d6f-0ecb170abf10)

2024-10-16 16:27 UTC, luke11brown commented on UK/Data/ASR/Newcastle/Newcastle Radar_1.asr
> +SECTORTITLE:
pls delete

2024-10-16 16:28 UTC, luke11brown commented on UK/Data/Plugin/TopSky_NERC/TopSkyMaps.txt
What's these changes?

2024-10-16 18:57 UTC, SamLefevre commented on UK/Data/Plugin/TopSky_NERC/TopSkyMaps.txt
Some VRP symbols should be displayed a triangle rather than the normal VRP symbol.

2024-10-28 04:09 UTC, luke11brown requested changes
As per other comments, everything else fine.

2024-10-28 04:09 UTC, luke11brown commented on UK/Data/ASR/Newcastle/Newcastle Radar_2.asr
> +SECTORTITLE:
Delete

2024-10-28 04:09 UTC, luke11brown commented on UK/Data/ASR/Newcastle/Newcastle Radar_3.asr
> +SECTORTITLE:
Delete

2024-10-28 04:09 UTC, luke11brown commented on UK/Data/ASR/Newcastle/Newcastle Radar_4.asr
> +SECTORTITLE:
Delete

2024-10-31 03:22 UTC, luke11brown approved these changes

2024-10-31 03:23 UTC, merged